<a href="https://www.kaggle.com/code/yesdodata/breast-cancer-type-prediction-using-a-basic-ann?scriptVersionId=177270219" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [2]:
df = pd.read_csv("/kaggle/input/cancer-dataset/wdbc.csv")

In [3]:
df

842302  M  17.99  10.38   122.8    1001   0.1184   0.2776   0.3001  \
0      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
1    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
2    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
3    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
4      843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
563    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
564    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
565    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
566    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
567     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

      0.1471  ...   25.38  17.33   184.6    2019   0.1622   0.6656  0.7119  \
0    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
1    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
2    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
3    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
4    0.08089  ...  15.470  23.75  103.40   741.6  0.17910  0.52490  0.5355   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
563  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
564  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
565  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
566  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
567  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

     0.2654  0.4601   0.1189  
0    0.1860  0.2750  0.08902  
1    0.2430  0.3613  0.08758  
2    0.2575  0.6638  0.17300  
3    0.1625  0.2364  0.07678  
4    0.1741  0.3985  0.12440  
..      ...     ...      ...  
563  0.2216  0.2060  0.07115  
564  0.1628  0.2572  0.06637  
565  0.1418  0.2218  0.07820  
566  0.2650  0.4087  0.12400  
567  0.0000  0.2871  0.07039  

[568 rows x 32 columns]

In [4]:
X = df.iloc[:,2:]
Y = df.iloc[:,1]

In [5]:
Y

0      M
1      M
2      M
3      M
4      M
      ..
563    M
564    M
565    M
566    M
567    B
Name: M, Length: 568, dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

In [7]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [9]:
X

array([[ 1.83208378, -0.35832707,  1.68910604, ...,  1.09526221,
        -0.24044363,  0.28529387],
       [ 1.58210603,  0.45385958,  1.56958968, ...,  1.96646779,
         1.16385786,  0.2053006 ],
       [-0.76711673,  0.25081292, -0.59077158, ...,  2.18809026,
         6.08623563,  4.95045676],
       ...,
       [ 0.70434323,  2.04789258,  0.6752776 , ...,  0.41969578,
        -1.10613122, -0.31576665],
       [ 1.84060575,  2.33962629,  1.98583632, ...,  2.30272257,
         1.93516598,  2.22846365],
       [-1.80679694,  1.22170271, -1.81313547, ..., -1.74761915,
        -0.04354852, -0.74961903]])

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Activation,Input

model = Sequential()
model.add(Dense(128, activation='sigmoid', input_shape=(30,)))
model.add(Dense(32, activation="sigmoid"))
model.add(Dense(1, activation="sigmoid"))

2024-05-12 19:15:21.309262: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-12 19:15:21.309392: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-12 19:15:21.470633: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         3,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,129 (31.75 KB)

 Trainable params: 8,129 (31.75 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics = ['accuracy'])

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [14]:
model.fit(X_train, Y_train, batch_size=256, epochs=100)

Epoch 1/100
1/2 ━━━━━━━━━━━━━━━━━━━━ 2s 3s/step - accuracy: 0.3594 - loss: 0.8631

I0000 00:00:1715541336.416367      71 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 747ms/step - accuracy: 0.3650 - loss: 0.8461
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3806 - loss: 0.7537 
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3624 - loss: 0.7005 
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6233 - loss: 0.6477 
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9064 - loss: 0.6122 
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8137 - loss: 0.5849 
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7510 - loss: 0.5659 
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7082 - loss: 0.5545 
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6974 - loss: 0.5458 
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7030 - loss: 0.5298 
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5206 
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7245 - loss: 0.5059 


In [15]:
pred = model.predict(X_test)
pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step


array([[0.9743224 ],
       [0.0328832 ],
       [0.04031751],
       [0.02204458],
       [0.030758  ],
       [0.9925229 ],
       [0.02580134],
       [0.9347243 ],
       [0.9861318 ],
       [0.02789404],
       [0.04518909],
       [0.8355905 ],
       [0.03556008],
       [0.9877002 ],
       [0.95309067],
       [0.97881466],
       [0.42619526],
       [0.02558201],
       [0.96098477],
       [0.98395306],
       [0.03450944],
       [0.02694676],
       [0.9918641 ],
       [0.06159927],
       [0.02957427],
       [0.45322004],
       [0.7045371 ],
       [0.02883234],
       [0.03709019],
       [0.97376597],
       [0.02422775],
       [0.11333717],
       [0.02300729],
       [0.03325228],
       [0.98822683],
       [0.02557518],
       [0.84790677],
       [0.05460773],
       [0.9909435 ],
       [0.02506119],
       [0.14697814],
       [0.9500726 ],
       [0.03183028],
       [0.9915247 ],
       [0.04656015],
       [0.8025525 ],
       [0.92796594],
       [0.990

In [16]:
pred = pred.round()
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(Y_test, pred))
print(confusion_matrix(Y_test, pred))


              precision    recall  f1-score   support

           0       1.00      0.99      0.99        70
           1       0.98      1.00      0.99        44

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

[[69  1]
 [ 0 44]]
